# Stubs for falcon.media (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import *
from .handlers import Handlers
from .json import JSONHandler
from .msgpack import MessagePackHandler
